### ISSUE TITLE
link copied but not downloading

### ISSUE THREAD

**Issue by khalilhoti** [yatochk/TikTokDownloader#2]
Hello sir when i copy link the toast shown downloading but file not downloading.

**Comment by WazirDeveloper93** [comment]
I am suffering from the same problem . copy link but doesnt give access to Application then and crushed

**Comment by yatochk** [comment]
Hello, can you provide information about the version of android? I will also be glad to get a crash stacktrace

**Comment by WazirDeveloper93** [comment]
Version : 3.5

**Comment by WazirDeveloper93** [comment]
I am sending you the crash SCS

**Comment by WazirDeveloper93** [comment]
Have you used any api  in this app yatochk

**Comment by WazirDeveloper93** [comment]
![scs2](https://user-images.githubusercontent.com/26427427/64093358-75087d80-cd71-11e9-93eb-48e95fbab8cb.PNG)
![scs3](https://user-images.githubusercontent.com/26427427/64093359-75a11400-cd71-11e9-817d-f8bda6708675.PNG)
![scs1](https://user-images.githubusercontent.com/26427427/64093360-75a11400-cd71-11e9-9750-7cec0199983b.PNG)

**Comment by WazirDeveloper93** [comment]
please bro guide me

**Comment by WazirDeveloper93** [comment]
I will pay for it

**Comment by bazantariq** [comment]
Appreciated developer. It is an amazing and outstanding application on GitHub community which I found. But Application is crashing when i past the video URL.
Its crashing while executing modelimpl.kt line#52 and line#31

E/AndroidRuntime: FATAL EXCEPTION: Thread-2911
Process: com.downloaderfor.tiktok, PID: 22439
java.lang.StringIndexOutOfBoundsException: length=0; index=-1
at java.lang.String.indexAndLength(String.java:500)
at java.lang.String.substring(String.java:1313)
at com.downloaderfor.tiktok.model.ModelImpl$downloadPreview$1.invoke(ModelImpl.kt:52)
at com.downloaderfor.tiktok.model.ModelImpl$downloadPreview$1.invoke(ModelImpl.kt:31)
at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
